
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: detect-private-key
      - id: flake8
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/ambv/black
    rev: 21.10b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
  - repo: https://github.com/dudefellah/pre-commit-openapi
    rev: "v0.0.1"
    hooks:
      - id: check-openapi



